apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: khanaliraza/my-react-app:latest
        ports:
        - containerPort: 80

---
# Service for deployment
apiVersion: v1
kind: Service
metadata:
  name: reactapp-serv
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
